# Generated by Django 5.1.4 on 2025-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovies',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
